apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-12-03T06:32:02Z"
  name: postgressv
  namespace: default
  resourceVersion: "64202"
  uid: 6d19e9d1-e136-48b9-8272-273a421758b5
spec:
  clusterIP: 10.101.151.45
  clusterIPs:
  - 10.101.151.45
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5433
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgressv
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
